version: '3.8'

services:
  postgres-db:
    image: postgres:14
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : root@123
      POSTGRES_DB : flyway
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name : flyway-demo-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL : jdbc:postgresql://postgres-db:5432/flyway
      SPRING_DATASOURCE_USERNAME : postgres
      SPRING_DATASOURCE_PASSWORD : root@123
    depends_on:
      - postgres-db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:

