spring:
  application:
    name: flyway-demo
    port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5432/flyway
    username: postgres
    password: root@123

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true